# Generated by Django 6.0.3 on 2026-03-06 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_id', models.CharField(choices=[('freemium', 'Freemium'), ('entry', 'Entry'), ('next', 'Next'), ('advanced', 'Advanced'), ('final_tier', 'Final')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=128)),
                ('price_africa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_usa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limit_africa', models.CharField(blank=True, max_length=32)),
                ('limit_usa', models.CharField(blank=True, max_length=32)),
                ('perks', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['tier_id'],
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('africa', 'Africa'), ('usa', 'USA')], default='africa', max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('freemium_airtime', 'Freemium airtime'), ('freemium_bill_pay', 'Freemium bill pay'), ('subscription', 'Subscription'), ('klarna_bnpl', 'Klarna BNPL')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=6)),
                ('gateway', models.CharField(choices=[('pawa_pay', 'PawaPay'), ('cellulant', 'Cellulant'), ('pay_pal', 'PayPal'), ('klarna', 'Klarna')], max_length=24)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.subscriptiontier')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.userlocation')),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
